# hadoint is a Dockerfile linter written in Haskell
# https://github.com/hadolint/hadolint

name: Docker Linter

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    - cron: '40 9 * * 6'

permissions:
  contents: read

jobs:
  hadolint:
    name: Run hadolint
    runs-on: ubuntu-latest
    permissions:
      contents: read          # for actions/checkout
      security-events: write  # for github/codeql-action/upload-sarif

    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Lint
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: ./Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      - name: Upload Results
        uses: github/codeql-action/upload-sarif@ddccb873888234080b77e9bc2d4764d5ccaaccf9
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true
