name: Mark Stale Issues and PRs

on:
  schedule:
  - cron: "30 1 * * *"

permissions:
  contents: read

jobs:
  stale:

    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-latest

    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Mark Stale
      uses: actions/stale@532554b8a8498a0e006fbcde824b048728c4178f
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        exempt-all-milestones: true
        stale-issue-message: 'This issue is stale because it has been open 90 days with no activity. Remove stale label or comment or this issue will be closed in 30 days.'
        stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this PR will be closed in 14 days.'
        close-issue-message: 'This issue was closed because it has been stale for 30 days with no activity.'
        close-pr-message: 'This PR was closed because it has been stale for 14 days with no activity.'
        days-before-issue-stale: 90
        days-before-pr-stale: 45
        days-before-issue-close: 30
        days-before-pr-close: 14
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        closed-issue-label: 'closed-stale'
        closed-pr-label: 'closed-stale'
